[build-system]
requires = [
    "setuptools>=64",
    "setuptools_scm>=8",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
dynamic = ["version"]
name = "{{ cookiecutter.package_name }}"
authors = [
    {name = "{{ cookiecutter.full_name }}", email = "{{ cookiecutter.email }}"}
]
description = "{{ cookiecutter.project_short_description }}"
readme = "README.rst"
classifiers = [
    "Development Status :: 1 - Planning",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]
dependencies = []

[project.urls]
Documentation = "http://{{ cookiecutter.package_name }}.readthedocs.io"
Repository = "https://github.com/{{ cookiecutter.github_username }}/{{ cookiecutter.package_name }}"

[project.optional-dependencies]
dev = [
    "{{ cookiecutter.project_slug }}[build,docs,lint,test]",
    "scriv",
    "tox"
]
test = [
    "coverage[toml]",
    "pytest",
]
lint = [
    "pre-commit"
]
build = [
    "build",
    "twine"
]
docs = [
    "sphinx",
    "sphinx_rtd_theme"
]

[tool.setuptools_scm]

[tool.ruff]
exclude = [
    "docs/**",
]
lint.ignore = [
    "D104"
]
line-length = 110
lint.select = [
    "B",
    "D",
    "E",
    "F",
    "I",
    "SIM",
    "UP",
    "W"
]

[tool.ruff.lint.per-file-ignores]
"src/{{ cookiecutter.project_slug }}/__init__.py" = [
    "E402",
    "F401",
    "F403"
]
"tests/**" = [
    "D101",
    "D102",
    "D103",
]

[tool.ruff.lint.isort]
force-sort-within-sections = true

[tool.ruff.lint.pydocstyle]
convention = "numpy"

[tool.ruff.lint.pycodestyle]
max-doc-length = 79

[tool.mypy]
ignore_missing_imports = true

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "EX01",
    "SA01",
    "ES01",
    "GL01",
    "SS05"
]
exclude = [
    "test_*",
    "__init__",
    "conf",
]