# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOXENV=py27
  - TOXENV=py35
  - TOXENV=style

python:
  - "3.5"
  - "2.7"
  - "pypy"

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install -r requirements.txt

# command to run tests, e.g. python setup.py test
script:
  - py.test

{% if cookiecutter.use_pypi_deployment_with_travis == 'y' -%}
# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: {{ cookiecutter.pypi_username }}
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: {{ cookiecutter.github_username }}/{{ cookiecutter.repo_name }}
    condition: $TOXENV == py35 && $TOXENV == py27
{%- endif %}
